#!/usr/bin/env bash
set -eo pipefail

if [ ! -z "$HS_HELP" ]; then
	[ ! -z "$HS_SHORT_HELP" ] && printf '%s\n' \
		'compile harp project';

	[ ! -z "$HS_USAGE_HELP" ] && printf '%s\n' '{COMMAND} [path]' \
		"compile all project's files to a static website" \
		'use the argument to set a custom output folder' \
		'[path] defaults to ./www' \
		'WARNING: the folder will be overwritten';

	[ ! -z "$HS_VARIABLES_HELP" ] && printf '%s\n' \
		'NO_CLEANUP: explicitly keep old files' \
		'NODE_ENV: specify node enviroment during compilation';
exit 0; fi;

outputPath="${1:-./www}"
[ -z "$NO_CLEANUP" ] && rm -r "$outputPath" 2> /dev/null || true;
NODE_ENV="${NODE_ENV:-production}" harp compile -o "$outputPath"
