#!/usr/bin/env bash
set -eo pipefail

if [ ! -z "$HS_HELP" ]; then
	[ ! -z "$HS_SHORT_HELP" ] && printf '%s\n' \
		'compile harp project';

	[ ! -z "$HS_USAGE_HELP" ] && printf '%s\n' '{COMMAND} [path]' \
		"compile all project's files to a static website" \
		'use the argument to set a custom output folder' \
		'[path] defaults to ./www/' \
		'WARNING: the folder will be overwritten';

	[ ! -z "$HS_VARIABLES_HELP" ] && printf '%s\n' \
		'HS_NODE_ENV: specify NODE_ENV during compilation';
exit 0; fi;

NODE_ENV="${HS_NODE_ENV:-production}" harp compile "$1"
