#!/usr/bin/env bash
set -eo pipefail

if [ ! -z "$HS_HELP" ]; then
	[ ! -z "$HS_SHORT_HELP" ] && printf '%s\n' \
		'run production server';

	[ ! -z "$HS_USAGE_HELP" ] && printf '%s\n' '{COMMAND}' \
		"serve project's assets via a http server" \
		'for live-reloading see `harp-scripts watch`';

	[ ! -z "$HS_VARIABLES_HELP" ] && printf '%s\n' \
		'PORT: specify port to listen on' \
		'HS_NODE_ENV: specify NODE_ENV for the server';
exit 0; fi;

NODE_ENV="${HS_NODE_ENV:-production}" \
harp server --port "$(get-port)"
