#!/usr/bin/env bash
set -eo pipefail

if [ ! -z "$HS_HELP" ]; then
	[ ! -z "$HS_SHORT_HELP" ] && printf '%s\n' \
		'test your project harp compilation'

	[ ! -z "$HS_VARIABLES_HELP" ] && printf '%s\n' \
		'HS_NODE_ENV: specify NODE_ENV during test';
exit 0; fi;

FOLDER_PREFIX="$(cat package.json | json name).harp-scripts-test"
NODE_ENV="${HS_NODE_ENV:-production}" \
harp compile -o "$(mktemp -dt "$FOLDER_PREFIX")"
