#!/usr/bin/env bash
set -eo pipefail

if [ ! -z "$HS_HELP" ]; then
	[ ! -z "$HS_SHORT_HELP" ] && printf '%s\n' \
		'concatenate javascript files';

	[ ! -z "$HS_USAGE_HELP" ] && printf '%s\n' '{COMMAND} jade_file' \
		'find script files from tags with data-uglify=true' \
		'and outputs joined file to STDOUT' \
		'local urls must be absolute!' \
		'' '{COMMAND} js_file [js_file...]' \
		'concatenate & minify files to STDOUT';
exit 0; fi;

get-files-jade(){
	cat "$1" | \
	grep 'script' | \
	sed -n "/data-uglify=['\"]true['\"]/p" | \
	awk -F '=' '/src/ {print $2}' | \
	awk -F "[\"']" '{print $(NF-1)}' | \
	sed 's|^/|./public/|'
}

get-config(){
	printf '%s%s%s\n' \
		'properties,dead_code,drop_debugger,unsafe,unsafe_comps,' \
		'conditionals,comparisons,evaluate,booleans,loops,unused,' \
		'if_return,join_vars,negate_iife,pure_getters'
}

uglify(){
	local input="$1"
	[ -z "$input" ] && echo 'InputError: Missing required argument: filename.' 1>&2 && exit 1
	local filetype="$("$(dirname "$0")/filetype" "$input" 2> /dev/null || false)"
	local files

	if [ "$filetype" = 'jade' ]; then
		files="$(get-files-jade "$input")"
	else
		files="$(printf '%s\n' "$@")"
	fi

	echo 'Uglify:' 1>&2
	echo "${files}" | nl -nrz -s': ' -w2 1>&2

	uglifyjs $files \
	--screw-ie8 \
	-c "$(get-config)" \
	-m --passes 10
}

uglify "$@"
