#!/usr/bin/env bash
set -eo pipefail

if [ ! -z "$HS_SHORT_HELP" ]; then
	echo 'concatenate javascript files'
	exit 0
fi

if [ ! -z "$HS_USAGE_HELP" ]; then
	echo '{COMMAND}'
	echo 'outputs joined file to STDOUT'
	echo 'automatically finds script files'
	exit 0
fi

if [ ! -z "$HS_VARIABLES_HELP" ]; then
	exit 0
fi

if [ ! -z "$HS_HIDE_HELP" ]; then
	exit 0
fi

files="$(cat public/_layout.jade | grep './scripts' | grep -v '.min.js' | tr -d '[:blank:]' | tr -d "'" | tr -d ')' | sed 's/script(src=//' | sed 's|^/|./public/|')"

echo 'compresing:' 1>&2
echo "${files}" 1>&2

uglifyjs \
$files \
--screw-ie8 \
-c properties,dead_code,drop_debugger,unsafe,unsafe_comps,conditionals,comparisons,evaluate,booleans,loops,unused,if_return,join_vars,negate_iife,pure_getters \
-m \
--passes 10 \
