#!/usr/bin/env bash
set -eo pipefail

if [ ! -z "$HS_HELP" ]; then
	[ ! -z "$HS_SHORT_HELP" ] && printf '%s\n' \
		'run a development server with browser-sync';

	[ ! -z "$HS_USAGE_HELP" ] && printf '%s\n' '{COMMAND}';

	[ ! -z "$HS_VARIABLES_HELP" ] && printf '%s\n' \
		'PORT: specify port to listen on';
exit 0; fi;

browser-sync start \
	--port "${PORT:-5000}" \
	--proxy "http://localhost:$((${PORT:-5000}+1))" \
	--files 'public' & \
harp server --port "$((${PORT:-5000}+1))"
